const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923184474176";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sʜᴇʟʟᴀʜ ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sʜᴇʟʟᴀʜ ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "SʜᴇʟᴛᴏɴMD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sʜᴇʟʟᴀʜ ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x shellah",

  sessionName:process.env.SESSION_ID || "SUHAIL_08_52_08_26_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgODAsXG4gICAgICAgIDExOCxcbiAgICAgICAgMTk4LFxuICAgICAgICAyMTUsXG4gICAgICAgIDEzNSxcbiAgICAgICAgMTY2LFxuICAgICAgICAxNDYsXG4gICAgICAgIDkyLFxuICAgICAgICA3OCxcbiAgICAgICAgMTk5LFxuICAgICAgICAxMTcsXG4gICAgICAgIDIzOCxcbiAgICAgICAgNjEsXG4gICAgICAgIDI1MCxcbiAgICAgICAgMTc3LFxuICAgICAgICAyLFxuICAgICAgICA5MyxcbiAgICAgICAgMjYsXG4gICAgICAgIDIwMSxcbiAgICAgICAgODksXG4gICAgICAgIDk1LFxuICAgICAgICAxODEsXG4gICAgICAgIDcyLFxuICAgICAgICAxMjUsXG4gICAgICAgIDEzNCxcbiAgICAgICAgMTksXG4gICAgICAgIDExMSxcbiAgICAgICAgMjA4LFxuICAgICAgICAyMDksXG4gICAgICAgIDE5MCxcbiAgICAgICAgMTE4LFxuICAgICAgICA4MVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMDIsXG4gICAgICAgIDg2LFxuICAgICAgICAyMDUsXG4gICAgICAgIDE4NixcbiAgICAgICAgMTIsXG4gICAgICAgIDE5OCxcbiAgICAgICAgNDIsXG4gICAgICAgIDE2MSxcbiAgICAgICAgMTk3LFxuICAgICAgICAxOTUsXG4gICAgICAgIDAsXG4gICAgICAgIDQ1LFxuICAgICAgICAxMTIsXG4gICAgICAgIDE3NSxcbiAgICAgICAgMTA2LFxuICAgICAgICAyMTgsXG4gICAgICAgIDU4LFxuICAgICAgICAyMTcsXG4gICAgICAgIDIxMyxcbiAgICAgICAgMjEyLFxuICAgICAgICAxMjUsXG4gICAgICAgIDE5OSxcbiAgICAgICAgNzEsXG4gICAgICAgIDcwLFxuICAgICAgICAyMjIsXG4gICAgICAgIDY2LFxuICAgICAgICAxODEsXG4gICAgICAgIDc2LFxuICAgICAgICAxMzksXG4gICAgICAgIDE4NyxcbiAgICAgICAgMjQ1LFxuICAgICAgICA4MVxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjE2LFxuICAgICAgICAzNCxcbiAgICAgICAgMTMzLFxuICAgICAgICAyMDMsXG4gICAgICAgIDI5LFxuICAgICAgICAxNjMsXG4gICAgICAgIDYzLFxuICAgICAgICAyMDUsXG4gICAgICAgIDE0OCxcbiAgICAgICAgMzAsXG4gICAgICAgIDU0LFxuICAgICAgICAyNTEsXG4gICAgICAgIDczLFxuICAgICAgICAyNTUsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMjA3LFxuICAgICAgICAyMyxcbiAgICAgICAgNTYsXG4gICAgICAgIDYzLFxuICAgICAgICAxMjQsXG4gICAgICAgIDIyNCxcbiAgICAgICAgMTg0LFxuICAgICAgICA2NixcbiAgICAgICAgMTI1LFxuICAgICAgICAyMDAsXG4gICAgICAgIDIwNSxcbiAgICAgICAgMzQsXG4gICAgICAgIDExNCxcbiAgICAgICAgODYsXG4gICAgICAgIDMsXG4gICAgICAgIDYwLFxuICAgICAgICA5OFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyNSxcbiAgICAgICAgMTQxLFxuICAgICAgICAyMzMsXG4gICAgICAgIDEsXG4gICAgICAgIDkyLFxuICAgICAgICAxMDEsXG4gICAgICAgIDIwMixcbiAgICAgICAgODMsXG4gICAgICAgIDE4NixcbiAgICAgICAgMTcxLFxuICAgICAgICA4NyxcbiAgICAgICAgMTg5LFxuICAgICAgICA4NixcbiAgICAgICAgMTgyLFxuICAgICAgICAxMSxcbiAgICAgICAgMTY5LFxuICAgICAgICA4OCxcbiAgICAgICAgMTk3LFxuICAgICAgICAxMzIsXG4gICAgICAgIDE3OSxcbiAgICAgICAgMjQ5LFxuICAgICAgICAzMSxcbiAgICAgICAgMTYwLFxuICAgICAgICAyNTUsXG4gICAgICAgIDEwMixcbiAgICAgICAgMjAyLFxuICAgICAgICAxMDQsXG4gICAgICAgIDQwLFxuICAgICAgICAzMixcbiAgICAgICAgNjYsXG4gICAgICAgIDE5MyxcbiAgICAgICAgMTVcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDI0MCxcbiAgICAgICAgMjQzLFxuICAgICAgICAxOTgsXG4gICAgICAgIDUzLFxuICAgICAgICAxNDYsXG4gICAgICAgIDIwOSxcbiAgICAgICAgMTksXG4gICAgICAgIDE5NCxcbiAgICAgICAgNzIsXG4gICAgICAgIDIwMixcbiAgICAgICAgMTIwLFxuICAgICAgICAxMTcsXG4gICAgICAgIDM5LFxuICAgICAgICA2MSxcbiAgICAgICAgNDAsXG4gICAgICAgIDE0MCxcbiAgICAgICAgMjQ0LFxuICAgICAgICAyNDMsXG4gICAgICAgIDE4NSxcbiAgICAgICAgODIsXG4gICAgICAgIDc1LFxuICAgICAgICAxMTksXG4gICAgICAgIDk1LFxuICAgICAgICA3LFxuICAgICAgICAyMzEsXG4gICAgICAgIDIzMixcbiAgICAgICAgOCxcbiAgICAgICAgMTYxLFxuICAgICAgICA0OCxcbiAgICAgICAgMTM0LFxuICAgICAgICAxLFxuICAgICAgICA5N1xuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA5NSxcbiAgICAgICAgMTk0LFxuICAgICAgICAyMzQsXG4gICAgICAgIDY5LFxuICAgICAgICAyNDMsXG4gICAgICAgIDIyOCxcbiAgICAgICAgMTE5LFxuICAgICAgICAyLFxuICAgICAgICAxMzEsXG4gICAgICAgIDExOSxcbiAgICAgICAgMTM3LFxuICAgICAgICAxMDcsXG4gICAgICAgIDY2LFxuICAgICAgICAyNTIsXG4gICAgICAgIDIzMSxcbiAgICAgICAgMjAxLFxuICAgICAgICAyNDQsXG4gICAgICAgIDM1LFxuICAgICAgICA1OSxcbiAgICAgICAgNjIsXG4gICAgICAgIDE0MCxcbiAgICAgICAgMzcsXG4gICAgICAgIDk3LFxuICAgICAgICAyOSxcbiAgICAgICAgMTQwLFxuICAgICAgICAxNjAsXG4gICAgICAgIDIyNyxcbiAgICAgICAgMTk5LFxuICAgICAgICAxMTUsXG4gICAgICAgIDIxMixcbiAgICAgICAgOSxcbiAgICAgICAgMTI1XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDEyOCxcbiAgICAgICAgICAxMDQsXG4gICAgICAgICAgMTM5LFxuICAgICAgICAgIDI0OCxcbiAgICAgICAgICAxMDksXG4gICAgICAgICAgODgsXG4gICAgICAgICAgOTMsXG4gICAgICAgICAgMTYwLFxuICAgICAgICAgIDM4LFxuICAgICAgICAgIDksXG4gICAgICAgICAgMzQsXG4gICAgICAgICAgMjQ0LFxuICAgICAgICAgIDgzLFxuICAgICAgICAgIDY3LFxuICAgICAgICAgIDIyMCxcbiAgICAgICAgICA3MixcbiAgICAgICAgICA5NCxcbiAgICAgICAgICA3NixcbiAgICAgICAgICAxODksXG4gICAgICAgICAgMTQxLFxuICAgICAgICAgIDUxLFxuICAgICAgICAgIDIxMyxcbiAgICAgICAgICAyMjQsXG4gICAgICAgICAgMTgzLFxuICAgICAgICAgIDE3NSxcbiAgICAgICAgICAzNCxcbiAgICAgICAgICAyNDQsXG4gICAgICAgICAgNjEsXG4gICAgICAgICAgNDQsXG4gICAgICAgICAgNzYsXG4gICAgICAgICAgNDksXG4gICAgICAgICAgNzFcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMTM5LFxuICAgICAgICAgIDEzOSxcbiAgICAgICAgICAyNTEsXG4gICAgICAgICAgODAsXG4gICAgICAgICAgNTYsXG4gICAgICAgICAgMjksXG4gICAgICAgICAgMTMzLFxuICAgICAgICAgIDQ5LFxuICAgICAgICAgIDc2LFxuICAgICAgICAgIDI4LFxuICAgICAgICAgIDE4MCxcbiAgICAgICAgICAxOTQsXG4gICAgICAgICAgMTczLFxuICAgICAgICAgIDE1NCxcbiAgICAgICAgICA1NCxcbiAgICAgICAgICAxOTksXG4gICAgICAgICAgMjA5LFxuICAgICAgICAgIDc2LFxuICAgICAgICAgIDEyNCxcbiAgICAgICAgICAxMixcbiAgICAgICAgICAzMixcbiAgICAgICAgICAxOTEsXG4gICAgICAgICAgMTYsXG4gICAgICAgICAgNzQsXG4gICAgICAgICAgMTMyLFxuICAgICAgICAgIDE3OSxcbiAgICAgICAgICA0NSxcbiAgICAgICAgICAyMixcbiAgICAgICAgICAxMTgsXG4gICAgICAgICAgMCxcbiAgICAgICAgICAxNjUsXG4gICAgICAgICAgNDZcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMyxcbiAgICAgICAgOTMsXG4gICAgICAgIDk3LFxuICAgICAgICAyNDMsXG4gICAgICAgIDEwLFxuICAgICAgICAxOTMsXG4gICAgICAgIDE2NSxcbiAgICAgICAgMjQsXG4gICAgICAgIDIyNSxcbiAgICAgICAgNTksXG4gICAgICAgIDE2OSxcbiAgICAgICAgNjcsXG4gICAgICAgIDE3NixcbiAgICAgICAgNjQsXG4gICAgICAgIDYyLFxuICAgICAgICAxMDksXG4gICAgICAgIDExNyxcbiAgICAgICAgMTg3LFxuICAgICAgICAxOTQsXG4gICAgICAgIDE0NyxcbiAgICAgICAgMjQ3LFxuICAgICAgICA1MCxcbiAgICAgICAgMjUyLFxuICAgICAgICAxOTksXG4gICAgICAgIDE5MSxcbiAgICAgICAgNDcsXG4gICAgICAgIDEyNCxcbiAgICAgICAgNDcsXG4gICAgICAgIDE4OSxcbiAgICAgICAgMTA1LFxuICAgICAgICAyMDAsXG4gICAgICAgIDIxNyxcbiAgICAgICAgMjIzLFxuICAgICAgICAxMzgsXG4gICAgICAgIDYyLFxuICAgICAgICA4OCxcbiAgICAgICAgMTMwLFxuICAgICAgICA0NixcbiAgICAgICAgMjgsXG4gICAgICAgIDQzLFxuICAgICAgICAyMDEsXG4gICAgICAgIDI3LFxuICAgICAgICAyMjgsXG4gICAgICAgIDE5MCxcbiAgICAgICAgMjI4LFxuICAgICAgICAyMTAsXG4gICAgICAgIDY1LFxuICAgICAgICAyMTEsXG4gICAgICAgIDE1MCxcbiAgICAgICAgNjUsXG4gICAgICAgIDIzNyxcbiAgICAgICAgNjEsXG4gICAgICAgIDEzMCxcbiAgICAgICAgMzMsXG4gICAgICAgIDIxOCxcbiAgICAgICAgMTI2LFxuICAgICAgICAyMjEsXG4gICAgICAgIDE3MixcbiAgICAgICAgMTM4LFxuICAgICAgICAxNjMsXG4gICAgICAgIDQ1LFxuICAgICAgICA1MCxcbiAgICAgICAgMjQ0LFxuICAgICAgICAxMzRcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDIyNyxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJuVkxsOHo2VHdrSVQ2eVBFRUUwNGRwYmJJRjEvcDhYeTljNjI5blAwOVRvPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjI2MzcxMzk1NDE2MEBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiNUU1QTVDMEU1MkExMkVFMEI5RTJFNDJCRENGQTRBNEFcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzI0NjYyMzE5XG4gICAgfSxcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiMjYzNzEzOTU0MTYwQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCI5Q0I3QjdGNTcyRjA0Q0MxODdBNTk5QjM2NTg5RjNFRFwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjQ2NjIzMjBcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDYxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDYxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAxLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwidXlIMjMtYlpTVUdSV0F2emZTX1FOd1wiLFxuICBcInBob25lSWRcIjogXCIyMzVjYzBkZi04ZDA1LTRjYzEtOTc3MS0yZWRlZjE3ZTkxMDVcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTkzLFxuICAgICAgODksXG4gICAgICAxNDUsXG4gICAgICAyNDgsXG4gICAgICAxMzUsXG4gICAgICAyMDUsXG4gICAgICAxMDIsXG4gICAgICAyMzAsXG4gICAgICA5LFxuICAgICAgMjM5LFxuICAgICAgNDIsXG4gICAgICAxMDAsXG4gICAgICAyNDcsXG4gICAgICA4NSxcbiAgICAgIDg2LFxuICAgICAgMTIyLFxuICAgICAgMTM3LFxuICAgICAgMjQ1LFxuICAgICAgOTcsXG4gICAgICAxNjZcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiB0cnVlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMzEsXG4gICAgICAxMTYsXG4gICAgICAxLFxuICAgICAgMTA5LFxuICAgICAgMjQ2LFxuICAgICAgMjQzLFxuICAgICAgNjcsXG4gICAgICAyMTMsXG4gICAgICAxMzAsXG4gICAgICA2MCxcbiAgICAgIDE0NCxcbiAgICAgIDEyLFxuICAgICAgNjEsXG4gICAgICAyMDUsXG4gICAgICAxMTAsXG4gICAgICA5OSxcbiAgICAgIDI1MSxcbiAgICAgIDEwOSxcbiAgICAgIDExNixcbiAgICAgIDE3OFxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25cIjoge30sXG4gIFwicGFpcmluZ0NvZGVcIjogXCJRWEtBS0szNVwiLFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiMjYzNzEzOTU0MTYwOjI5QHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJsaWRcIjogXCIyMjc5MTcyMzc4OTUzMDY6MjlAbGlkXCIsXG4gICAgXCJuYW1lXCI6IFwi4bS54bS/4a2EIPCdlrLwnZeB8J2WvvCdl4XwnZeF8J2WuvCdl4Eg4bSP0pPhtIQqXCJcbiAgfSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDTTM3dkxvQkVLbUVzYllHR0FNZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJwMytWUUVHZ003aUJvRTRNOFQ5aitPbVh4UHdaNUdlQkNIbWR1SUxieUVZPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcIkdvRGFFOEhDKzI3UmJpbWZWRnREcmQ5dWsrMnpRSlJkL0JuMHFYekFIMzAvUnJQTGd6Rzcxd3FCR1Nzd0FOcE1DeUdCWjJ5S3BIaGs5cUtBZmJqR0RnPT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcIk9FSU9pdkhKdDJDRWJnNUxFRWljNncvT0F2VHduV0YrYkNvRGk5Qk5FaStpRUw0Y3RGWFhUSnlPME1jc2RSeTI1REd4UUFlMjdUc0U2R25zdVovOGh3PT1cIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjI2MzcxMzk1NDE2MDoyOUBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDE2NyxcbiAgICAgICAgICAxMjcsXG4gICAgICAgICAgMTQ5LFxuICAgICAgICAgIDY0LFxuICAgICAgICAgIDY1LFxuICAgICAgICAgIDE2MCxcbiAgICAgICAgICA1MSxcbiAgICAgICAgICAxODQsXG4gICAgICAgICAgMTI5LFxuICAgICAgICAgIDE2MCxcbiAgICAgICAgICA3OCxcbiAgICAgICAgICAxMixcbiAgICAgICAgICAyNDEsXG4gICAgICAgICAgNjMsXG4gICAgICAgICAgOTksXG4gICAgICAgICAgMjQ4LFxuICAgICAgICAgIDIzMyxcbiAgICAgICAgICAxNTEsXG4gICAgICAgICAgMTk2LFxuICAgICAgICAgIDI1MixcbiAgICAgICAgICAyNSxcbiAgICAgICAgICAyMjgsXG4gICAgICAgICAgMTAzLFxuICAgICAgICAgIDEyOSxcbiAgICAgICAgICA4LFxuICAgICAgICAgIDEyMSxcbiAgICAgICAgICAxNTcsXG4gICAgICAgICAgMTg0LFxuICAgICAgICAgIDEzMCxcbiAgICAgICAgICAyMTksXG4gICAgICAgICAgMjAwLFxuICAgICAgICAgIDcwXG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJhbmRyb2lkXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MjQ2NjIzMTcsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFOeXlcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQU55eS5qc29uIjogIntcImtleURhdGFcIjpcImF3SkVSSzd0STMyT2pkMHdnNWg2T29LbytjelNPYjU2N1h3Zkhnd1dTcXc9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MzkxMDY5MTMzLFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MjQ2NTY1MDQyNTZcIn0iCn0="  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
